/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
-----------------------------------------------------
 ► Cliente URL embebido en una ventana para medir el 
tiempo empleado por el Servidor en enviar un recurso
(Tiempo empleado por el Servidor en enviar un recurso 
" Tiempo de transmision " ) 

*/
package t5pag24tiempotransmisionurl;

import java.awt.HeadlessException;

/**
 *
 * @author InTylerWeTrust
 */
public class Ventana extends javax.swing.JFrame {
 
// Constructor de la ventana : llamado por el metodo main de abajo cuando
// la aplicacion se inicia 
 public Ventana() throws HeadlessException {
//  inicia los componentes de diseño
  initComponents();
  jTextField1.setText("http://arxiv.org/pdf/1112.0922");
 }
 /**
  This method is called from within the constructor to initialize the form
 WARNING : Do NOT MODIFY this code 
 The content of this method is always regenerated by the Form Editor
 */
 @SuppressWarnings("unchecked")
//<editor-fold defaultstate="collapsed" desc="Generated Code"> //GEN-BEGIN:initComponents
private void initComponents(){
 
// Componentes 
 jPanel1 = new javax.swing.JPanel();
 jButton1 = new javax.swing.JButton();
 jTextField1 = new javax.swing.JTextField();
 jLabel1 = new javax.swing.JLabel();
 jLabel2 = new javax.swing.JLabel();
 jLabel3 = new javax.swing.JLabel();
 
// Cerrar por defecto la ventana mediante la opción de la pestaña de cerrar
 setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 
 jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null,"Recursos URL",javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,javax.swing.border.TitledBorder.DEFAULT_POSITION,new java.awt.Font("Tahoma",0,11),new java.awt.Color(51,153,255))); //NOI18N
 
  jButton1.setText("Iniciar Trasmision y medir el tiempo");
  jButton1.addActionListener(new java.awt.event.ActionListener(){
// ♦ Metodo .add   
public void actionPerformed(java.awt.event.ActionEvent evt){
   jButton1ActionPerformed(evt);
}
});

jTextField1.setToolTipText("");

jLabel2.setText("Nota : para que las medidas sean fiables , hay que sincronizar inmediatamente");

jLabel3.setText(" Antes el Reloj del PC con un Servidor Horario de Internet");

// Crea Objeto jPanel1Layout
javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
// Asocia al Objeto jPanel1
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
// ♦ Metodo .add         
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,jPanel1Layout.createSequentialGroup().addGap(0,168,Short.MAX_VALUE)
.addComponent(jButton1))
.addGroup(jPanel1Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jTextField1,javax.swing.GroupLayout.DEFAULT_SIZE,359,Short.MAX_VALUE).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,jPanel1Layout.createSequentialGroup()
.addGap(0,0,Short.MAX_VALUE)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel2)
.addComponent(jLabel3))
.addContainerGap())))
);
 
//Asocia al objeto jPanel1Layout metodos encesarios 
jPanel1Layout.setVerticalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
// ♦ Metodo .add         
 .addGroup(jPanel1Layout.createSequentialGroup()
.addComponent(jTextField1,javax.swing.GroupLayout.PREFERRED_SIZE,
     javax.swing.GroupLayout.DEFAULT_SIZE,javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jLabel2)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,javax.swing.GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
.addComponent(jLabel3)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jButton1))
);
 
jLabel1.setText("Tiempo Transmision Recurso URL");

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
// ♦ Metodo .add   
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jPanel1,javax.swing.GroupLayout.DEFAULT_SIZE,javax.swing.GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
.addGroup(layout.createParallelGroup()
.addComponent(jLabel1)
.addGap(0,224,Short.MAX_VALUE)))
.addContainerGap())
);

layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
// ♦ Metodo .add    
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,layout.createSequentialGroup()
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
.addComponent(jLabel1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jPanel1,javax.swing.GroupLayout.PREFERRED_SIZE,javax.swing.GroupLayout.DEFAULT_SIZE,javax.swing.GroupLayout.PREFERRED_SIZE))
);
// ♦ Metodo .add   
pack();
} // </editor-fold>//GEN-END:initComponents
 
/***************************************************************************
 * Responde al clic en el boton "Iniciar Transmision y medir el Tiempo'
*/

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt){
//GEN-FIRST:event_jButton1ActionPerformed
//crea un hilo para la URL introducida
HiloBoton hiloCliente = new HiloBoton(jTextField1.getText());
//solicita su ejecucion
hiloCliente.start();
}//GEN-LAST:event_jButton1ActionPerformed

/*
@param args the command line arguments
*/

public static void main(String args[]) throws IllegalAccessException{
/*
Set the Nimbus look and feel
//<editor-fold defaultstate="collapsed" desc="Look and feel setting code(optional)">
 
/*
  * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
// ↕ INTENTA
 try {
//  ♠ BUCLE
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
//  ♠ BUCLE
if ("Nimbus".equals(info.getName())) {
   javax.swing.UIManager.setLookAndFeel(info.getClassName());
   break;
  }
 }
}catch(ClassNotFoundException ex){
java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
}catch(InstantiationException ex){
java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
}catch(IllegalAccessException ex){
java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
}catch(javax.swing.UnsupportedLookAndFeelException ex){
 java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
}
//</editor-fold>

 /*
 Create and display the form
*/
java.awt.EventQueue.invokeLater(new Runnable(){
 // ♦ Metodo  
// ♦ HILO
 @Override
 public void run(){
    new Ventana().setVisible(true);
  }
});
}
// Variable declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton jButton1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JPanel jPanel1;
private javax.swing.JTextField jTextField1;
// End of variable declaration//GEN-END:variables
}




















